name: purevideo
description: ""
publish_to: "none"
version: 0.0.0+0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  dio: ^5.3.3
  get_it: ^8.0.3
  go_router: ^14.8.1
  hive: ^2.2.3
  html: ^0.15.4
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  chewie: ^1.7.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.2.2

  async: any
  video_player: any
  wakelock_plus: any
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  visibility_detector: ^0.4.0+2
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  screen_brightness: ^2.1.3
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
